"""Pydantic + JSON schema for daily news writer strict output.

The OpenAI ``response_format={"type": "json_schema", "strict": true, ...}``
mode rejects responses where ``citations[].url`` is not in the enum built from
the fact-pack allowlist. Body text references citations by ``[CITE_N]`` rather
than inline ``[N](URL)``; substitution happens in
``services.agents.citation_substitution``.

Daily quizzes are generated by a separate quiz-only call after body quality
checks. This schema intentionally covers article body, frontload metadata, and
source-card metadata only.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, field_validator


class Citation(BaseModel):
    n: int = Field(ge=1, le=50)
    url: str = Field(min_length=1)

    @field_validator("url")
    @classmethod
    def url_must_be_http(cls, v: str) -> str:
        if not (v.startswith("http://") or v.startswith("https://")):
            raise ValueError("url must start with http(s)://")
        return v


class SourceEntry(BaseModel):
    """Writer-supplied source card metadata."""

    id: int = Field(ge=1, le=50)
    url: str = Field(min_length=1)
    title: str = ""


class NewsWriterOutput(BaseModel):
    headline: str
    headline_ko: str
    excerpt: str
    excerpt_ko: str
    en: str
    ko: str
    citations: list[Citation]
    tags: list[str]
    focus_items: list[str]
    focus_items_ko: list[str]
    sources: list[SourceEntry]


def build_news_writer_json_schema(allowlist_urls: list[str]) -> dict[str, Any]:
    """Build an OpenAI strict json_schema with citations[].url as an enum."""

    if not allowlist_urls:
        raise ValueError(
            "Cannot build writer schema with empty allowlist; "
            "fact_pack.news_items must have at least one URL."
        )

    seen: set[str] = set()
    unique: list[str] = []
    for url in allowlist_urls:
        if url not in seen:
            seen.add(url)
            unique.append(url)

    return {
        "name": "news_writer_output",
        "strict": True,
        "schema": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "headline",
                "headline_ko",
                "excerpt",
                "excerpt_ko",
                "en",
                "ko",
                "citations",
                "tags",
                "focus_items",
                "focus_items_ko",
                "sources",
            ],
            "properties": {
                "headline": {"type": "string"},
                "headline_ko": {"type": "string"},
                "excerpt": {"type": "string"},
                "excerpt_ko": {"type": "string"},
                "en": {"type": "string"},
                "ko": {"type": "string"},
                "citations": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "required": ["n", "url"],
                        "properties": {
                            "n": {"type": "integer", "minimum": 1, "maximum": 50},
                            "url": {"type": "string", "enum": unique},
                        },
                    },
                },
                "tags": {"type": "array", "items": {"type": "string"}},
                "focus_items": {"type": "array", "items": {"type": "string"}},
                "focus_items_ko": {"type": "array", "items": {"type": "string"}},
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "required": ["id", "url", "title"],
                        "properties": {
                            "id": {"type": "integer", "minimum": 1, "maximum": 50},
                            "url": {"type": "string"},
                            "title": {"type": "string"},
                        },
                    },
                },
            },
        },
    }
