-- 00022_seed_ai_products.sql
-- Seed AI product drafts from bookmarks (2025-03-15)

-- =============================================================================
-- 1. New categories
-- =============================================================================
INSERT INTO ai_product_categories (id, label_en, label_ko, description_en, description_ko, icon, sort_order)
VALUES
  ('platform', 'AI Platforms & DevOps', 'AI 플랫폼/운영',
    $desc$Your AI stack needs more than a model. Manage API keys, track costs, set rate limits, and run LLM gateways across your entire team without reinventing the wheel. PortKey, LangFuse, and Helicone make production AI ops manageable.$desc$,
    $desc$AI 모델 하나로는 부족합니다. API 키 관리, 비용 추적, 속도 제한, LLM 게이트웨이까지 — 팀 전체의 AI 운영 인프라를 한 곳에서 관리하세요. PortKey, LangFuse, Helicone이 프로덕션 AI 운영을 간단하게 만들어 줍니다.$desc$,
    '🛠️', 8),
  ('research', 'Research & Papers', '리서치/논문',
    $desc$Stay ahead without drowning in PDFs. Search millions of papers, get AI-generated summaries, and track citations across the latest breakthroughs in machine learning and AI. arXiv, Semantic Scholar, and Paper Digest are essential starting points.$desc$,
    $desc$PDF의 홍수에 빠지지 않고도 최신 연구를 따라갈 수 있습니다. 수백만 편의 논문을 검색하고, AI 요약을 받고, 최신 연구의 인용 흐름을 추적해 보세요. arXiv, Semantic Scholar, Paper Digest가 출발점입니다.$desc$,
    '🔬', 9),
  ('community', 'Communities & Resources', '커뮤니티/리소스',
    $desc$The best AI insights rarely come from press releases. Follow researchers, engineers, and builders on Reddit, Hacker News, and Discord communities where breakthroughs are debated the moment they drop.$desc$,
    $desc$최고의 AI 인사이트는 보도자료에 없습니다. Reddit, Hacker News, Discord 커뮤니티에서 연구자와 엔지니어들이 나누는 실시간 토론을 따라가 보세요. 새로운 발견이 나오는 순간 현장에서 바로 확인할 수 있습니다.$desc$,
    '🌐', 10)
ON CONFLICT (id) DO UPDATE SET
  label_en        = EXCLUDED.label_en,
  label_ko        = EXCLUDED.label_ko,
  description_en  = EXCLUDED.description_en,
  description_ko  = EXCLUDED.description_ko,
  icon            = EXCLUDED.icon,
  sort_order      = EXCLUDED.sort_order;

-- =============================================================================
-- 2. Product drafts (156 entries)
-- =============================================================================
INSERT INTO ai_products (slug, name, url, tagline_ko, primary_category, is_published)
VALUES
  ('ada', 'ADA', 'https://www.adaglobal.com/ko', 'AI 튜터 | 학습 | 체계적 학습코스', 'assistant', false),
  ('canva', 'Canva', 'https://www.canva.com/ko_kr/', '디자인/슬라이드 | 빠른 제작 | 비디자이너도 가능', 'assistant', false),
  ('chatgpt', 'ChatGPT', 'https://chat.openai.com/', '대화형 LLM | 초안/코드리뷰 | 범용성+빠른응답', 'assistant', false),
  ('claude', 'Claude', 'https://claude.ai/new', 'LLM(Claude) | 긴글/추론 | 긴 맥락 이해력', 'assistant', false),
  ('clova-x', 'CLOVA X', 'https://clova-x.naver.com/', '네이버 LLM | 한국어 | 한국어 특화모델', 'assistant', false),
  ('cue', 'Cue', 'https://search.naver.com/search.naver?query=Cue%3A&cue=0&where=nexearch&sm=cue_clk.wait', '네이버 AI검색 | 요약·탐색 | 국내 정보 검색특화', 'assistant', false),
  ('gamma', 'Gamma', 'https://gamma.app/ko/products/presentations', 'AI 슬라이드 | 발표자료 | 텍스트→슬라이드 생성', 'assistant', false),
  ('gemini', 'Gemini', 'https://gemini.google.com/', 'Google LLM | 리서치/요약 | 구글 생태계 통합', 'assistant', false),
  ('genspark', 'Genspark', 'https://www.genspark.ai/', 'AI 에이전트 | 리서치/자동화 | 멀티에이전트 워크플로우', 'assistant', false),
  ('grok', 'Grok', 'https://grok.com/', 'xAI 챗봇 | 실시간 탐색 | 실시간 X데이터 접근', 'assistant', false),
  ('hugging-face', 'Hugging Face', 'https://huggingface.co/', '모델허브(HF) | 모델 찾기 | 오픈소스 모델 중심지', 'assistant', false),
  ('llama', 'Llama', 'https://www.llama.com/', 'LLM 모델 | Llama | 오픈소스 LLM', 'assistant', false),
  ('meta-ai-demos', 'Meta AI Demos', 'https://aidemos.meta.com/segment-anything/gallery', 'Meta 데모 | SAM 등 | 신기술 직접체험', 'assistant', false),
  ('moltbot-personal-ai-assistant', 'Moltbot — Personal AI Assistant', 'https://clawd.bot/', NULL, 'assistant', false),
  ('notebooklm', 'NotebookLM', 'https://notebooklm.google.com/', '문서 기반 LLM | 자료 Q&A | 문서 기반 질문응답', 'assistant', false),
  ('openclaw', 'OpenClaw', 'https://openclaw.ai/', '개인 AI 어시스턴트 | 개인 업무 자동화 시 | 프라이빗 AI', 'assistant', false),
  ('perplexity', 'Perplexity', 'https://www.perplexity.ai/', '검색형 AI | 근거 찾기 | 출처링크 자동첨부', 'assistant', false),
  ('qanda', 'QANDA', 'https://qanda.ai/ko', 'AI Q&A | 학습/질문 | 학습 질문 즉시해결', 'assistant', false),
  ('skywork', 'skywork', 'https://skywork.ai/', 'AI 워크스페이스 | 검색/요약 | 작업 통합관리', 'assistant', false),
  ('slidesai', 'SlidesAI', 'https://www.slidesai.io/ko', 'AI 슬라이드 | 문서→PPT | 문서 빠른변환', 'assistant', false),
  ('elevenlabs', 'ElevenLabs', 'https://elevenlabs.io/', 'TTS/보이스 | 영어 | 고품질 영어음성', 'audio', false),
  ('suno', 'Suno', 'https://suno.com/', '텍스트→완성 노래 생성 | AI 음악 제작 시 | 음악 생성 현재 1위', 'audio', false),
  ('suno-ai', 'Suno AI', 'https://suno.ai/', 'AI 음악 | 작곡 | AI 음악 생성', 'audio', false),
  ('supertone-play', 'Supertone Play', 'https://play.supertone.ai/', '보이스 | 음성 | 음성 변환기술', 'audio', false),
  ('udio', 'Udio', 'https://udio.com/', '세밀한 AI 음악 편집·생성 | 음악 구조 직접 컨트롤 시 | Suno 대안', 'audio', false),
  ('apidog', 'Apidog', 'https://apidog.com/ko-KR/', 'API 설계/테스트 | Postman 대체 | Mock API생성', 'builder', false),
  ('bolt.new', 'Bolt.new', 'https://bolt.new/', 'AI 풀스택 | 웹앱 즉시 | 웹앱 즉시생성', 'builder', false),
  ('dify', 'Dify', 'https://dify.ai/', 'LLM 앱 빌더 | 챗봇/워크플로우 | 빠른 LLM앱 구축', 'builder', false),
  ('flowise', 'Flowise', 'https://flowiseai.com/', 'LLM 플로우 | 노코드 체인 | 노코드 LLM체인', 'builder', false),
  ('incerto', 'Incerto', 'https://incerto.in/', 'DB AI Copilot | 쿼리/인사이트 | 자연어 DB조회', 'builder', false),
  ('langflow', 'LangFlow', 'https://www.langflow.org/', '플로우 빌더 | 체인 구성 | UI로 체인구성', 'builder', false),
  ('langsmith', 'LangSmith', 'https://smith.langchain.com/o/a513af5e-fe2d-43d0-a457-14049638ce56/', 'LLM 관측/트레이싱 | 디버깅 | 품질+비용 최적화', 'builder', false),
  ('lovable', 'Lovable', 'https://lovable.dev/', 'AI 앱 생성 | 아이디어→앱 | 아이디어→앱 즉시생성', 'builder', false),
  ('pinecone', 'Pinecone', 'https://app.pinecone.io/organizations/-OZglGtrnBoM-sqJvolT/projects/6cc98481-e95f-4c75-8ced-092d4937d029/indexes', '벡터DB 콘솔 | RAG 구축 | 유사도 검색엔진', 'builder', false),
  ('tavily', 'Tavily', 'https://www.tavily.com/', '검색 API | 에이전트 검색 | LLM최적화 검색결과', 'builder', false),
  ('v0', 'v0', 'https://v0.dev/', 'UI 생성 | 컴포넌트 | Vercel UI생성기', 'builder', false),
  ('webflow', 'Webflow', 'https://webflow.com/', '웹빌더 | 마케팅 사이트 | 마케팅 사이트 배포', 'builder', false),
  ('anima', 'Anima', 'https://www.animaapp.com/', 'Figma→코드 | 프론트 | Figma→코드 변환', 'coding', false),
  ('antigravity', 'Antigravity 소개 블로그', 'https://antigravity.google/blog/introducing-google-antigravity', 'Antigravity 공식 소개 | 설계 철학·구조 이해 시 | 자율 에이전트 IDE 이해 필수', 'coding', false),
  ('antigravity-getting-started', 'Antigravity Getting Started', 'https://codelabs.developers.google.com/getting-started-google-antigravity', 'Antigravity 핸즈온 튜토리얼 | 처음 사용 시작 시 | 공식 코드랩', 'coding', false),
  ('bubble', 'Bubble', 'https://bubble.io/', '노코드 앱 | 빠른 MVP | 빠른 MVP 제작', 'coding', false),
  ('chacha95-advanced-harness', 'chacha95/advanced-harness', 'https://github.com/chacha95/advanced-harness', 'LLM 고급 평가 프레임워크 | 모델 벤치마크·테스트 시 | 고급 하네스 도구', 'coding', false),
  ('claude-code-is-a-beast', 'Claude Code is a Beast', 'https://www.reddit.com/r/ClaudeAI/comments/1oivjvm/claude_code_is_a_beast_tips_from_6_months_of/', 'Claude Code 실사용 팁 | 실전 활용법 수집 시 | 6개월 경험 정리 커뮤니티', 'coding', false),
  ('codex-cli', 'Codex CLI', 'https://github.com/openai/codex', '터미널 AI 코딩 에이전트 | CLI 환경 AI 코딩 시 | Claude Code 경쟁 오픈소스', 'coding', false),
  ('codex-web', 'Codex Web', 'https://platform.openai.com/codex', '브라우저 AI 코딩 에이전트 | 백그라운드 병렬 코딩 작업 시 | OpenAI 공식 코딩 에이전트', 'coding', false),
  ('coleam00-second-brain-skills-a-collection-of-claude-skills-to-turn-claude-code-into-a-second-brain', 'coleam00/second-brain-skills: A collection of Claude Skills to turn Claude Code into a Second Brain', 'https://github.com/coleam00/second-brain-skills', NULL, 'coding', false),
  ('cursor', 'Cursor', 'https://cursor.com/', 'AI IDE | 코딩 | AI 코딩 보조IDE', 'coding', false),
  ('extend-claude-code', 'Extend Claude Code', 'https://code.claude.com/docs/en/features-overview', 'Claude Code 확장 기능 | 플러그인·기능 확장 시 | 공식 기능 가이드', 'coding', false),
  ('firebase-studio', 'Firebase Studio', 'https://studio.firebase.google.com/', 'AI 풀스택 IDE | AI 앱 빌드·배포 시 | 구글 AI 통합 개발환경', 'coding', false),
  ('gemini-cli', 'Gemini CLI', 'https://github.com/google-gemini/gemini-cli', '구글 오픈소스 터미널 에이전트 | 무료 AI 코딩 에이전트 필요 시 | 분당 60 req 무료', 'coding', false),
  ('github-copilot', 'GitHub Copilot', 'https://github.com/features/copilot', '코딩 보조 | 자동완성 | 코드 자동완성', 'coding', false),
  ('google-antigravity', 'Google Antigravity', 'https://antigravity.google/', '구글 실험 프로젝트 | 호기심 탐색 시 | 구글 재미 이스터에그', 'coding', false),
  ('how-claude-code-works', 'How Claude Code works', 'https://code.claude.com/docs/en/how-claude-code-works', 'Claude Code 동작 원리 | 내부 구조 이해 시 | 아키텍처 파악', 'coding', false),
  ('keras', 'Keras', 'https://keras.io/', 'DL API | 빠른 실험 | 프로토타입 빠른생성', 'coding', false),
  ('manage-claudes-memory', 'Manage Claude''s memory', 'https://code.claude.com/docs/en/memory', 'Claude 메모리 관리 | 컨텍스트 지속 설정 시 | 기억 유지 방법', 'coding', false),
  ('minusx-what-makes-claude-code-so-damn-good', 'Minusx | What makes Claude Code so damn good', 'https://minusx.ai/blog/decoding-claude-code/?utm_source=tldrnewsletter#11-keep-one-main-loop', 'Claude Code 심층 분석 | 에이전트 설계 학습 시 | 내부 동작 인사이트', 'coding', false),
  ('openai-agents-sdk', 'OpenAI Agents SDK', 'https://github.com/openai/openai-agents-python', 'OpenAI 공식 에이전트 Python SDK | AI 에이전트 개발 시 | OpenAI 에이전트 프레임워크', 'coding', false),
  ('pytorch', 'PyTorch', 'https://pytorch.org/', 'DL 프레임워크 | 연구/학습 | 연구+실험 유연성', 'coding', false),
  ('replit-ai', 'Replit AI', 'https://replit.com/', '클라우드 IDE | 실행/배포 | 클라우드 실행+배포', 'coding', false),
  ('scikit-learn', 'Scikit-learn', 'https://scikit-learn.org/', 'ML 라이브러리 | 베이스라인 | 빠른 베이스라인 구축', 'coding', false),
  ('stitch', 'Stitch', 'https://stitch.withgoogle.com/', '구글 Stitch | 프로토타입 생성 | 노코드 UI생성', 'coding', false),
  ('tabnine', 'Tabnine', 'https://www.tabnine.com/', '코딩 보조 | 기업용 | 기업용 코딩보조', 'coding', false),
  ('tensorflow', 'TensorFlow', 'https://www.tensorflow.org/', 'DL 프레임워크 | 모델 학습 | 프로덕션 배포 최적화', 'coding', false),
  ('the-agent-skills-directory', 'The Agent Skills Directory', 'https://skills.sh/', '에이전트 스킬 디렉토리 | AI 에이전트 도구 탐색 시 | 스킬 레퍼런스 모음', 'coding', false),
  ('vibe-index', 'Vibe Index', 'https://www.vibeindex.ai/', '바이브 코딩 디렉토리 | AI 코딩 도구 탐색 시 | 트렌디한 바이브코딩 모음', 'coding', false),
  ('windsurf', 'Windsurf', 'https://codeium.com/windsurf', 'IDE+AI | 코딩 | AI 통합 IDE', 'coding', false),
  ('geeknews', 'GeekNews', 'https://news.hada.io/', 'IT 뉴스 | 큐레이션 | IT뉴스 큐레이션', 'community', false),
  ('hacker-news', 'Hacker News', 'https://news.ycombinator.com/', '커뮤니티 | 테크 뉴스 | 최신 테크뉴스', 'community', false),
  ('it', '요즘IT', 'https://yozm.wishket.com/', 'IT 아티클 | 실무 | 실무 IT아티클', 'community', false),
  ('latent.space', 'Latent.Space', 'https://www.latent.space/', 'AI 글 | 트렌드 | AI 트렌드 글', 'community', false),
  ('n8n-korea', 'n8n Korea', 'https://slashpage.com/n8n-korea', '커뮤니티 | n8n | n8n 한국 커뮤니티', 'community', false),
  ('phdkim', '김박사넷', 'https://phdkim.net/', '연구자 커뮤니티 | 진학/논문 | 대학원 정보공유', 'community', false),
  ('pseudo-lab', '가짜연구소 (Pseudo Lab)', 'https://chanrankim.notion.site/Pseudo-Lab-c42db6652c1b45c3ba4bfe157c70cf09', 'ML 커뮤니티 | 스터디/프로젝트 | ML 스터디+프로젝트', 'community', false),
  ('reddit', 'reddit', 'https://www.reddit.com/', '커뮤니티 | 실사용 팁 | 실사용 경험공유', 'community', false),
  ('stack-overflow', 'Stack Overflow', 'https://stackoverflow.com/', 'Q&A | 에러 해결 | 에러 해결 Q&A', 'community', false),
  ('theres-an-ai-for-that', 'There''s An AI For That', 'https://theresanaiforthat.com/dashboard/', 'AI툴 디렉토리 | 툴 찾을 때 | AI툴 검색엔진', 'community', false),
  ('adobe-firefly', 'Adobe Firefly', 'https://firefly.adobe.com/', '상업 안전 이미지 생성 | 저작권 걱정 없는 이미지 필요 시 | 100% 라이선스 클린', 'image', false),
  ('ai-pixai', 'AI 작품 생성기 | PixAI', 'https://pixai.art/ko/generator/image', 'AI 이미지 생성기 | 애니 스타일 이미지 제작 시 | 무료 생성 가능', 'image', false),
  ('ai-seaart-ai', '예술, 비디오, 채팅 및 도구를 위한 AI 창작 커뮤니티 - SeaArt AI', 'https://www.seaart.ai/ko', 'AI 이미지 커뮤니티 | AI 아트 생성·공유 시 | 아시아 특화 플랫폼', 'image', false),
  ('dall-e-3', 'DALL-E 3', 'https://openai.com/dall-e-3', '이미지 생성 | DALL·E | 텍스트 이해 정확성', 'image', false),
  ('dribbble', 'Dribbble', 'https://dribbble.com/', '디자인 레퍼런스 | 영감 | 디자인 트렌드 파악', 'image', false),
  ('figcomponents', 'Figcomponents', 'https://www.figcomponents.com/', '컴포넌트 | UI 레퍼런스 | UI 컴포넌트 참고', 'image', false),
  ('figma', 'Figma', 'https://www.figma.com/', 'UI 디자인 | 협업 | 실시간 협업디자인', 'image', false),
  ('flux', 'Flux', 'https://flux-ai.io/flux-ai-image-generator/', '이미지 생성 | FLUX | 고품질 이미지', 'image', false),
  ('heygen-ai-video-generator', 'HeyGen - AI Video Generator', 'https://www.heygen.com/', '아바타 영상 | 마케팅 | 아바타 영상 생성', 'image', false),
  ('ideogram', 'Ideogram', 'https://ideogram.ai/', '이미지 텍스트 삽입 1위 | 이미지 안에 글자 넣을 때 | 타 도구 압도적 우위', 'image', false),
  ('jordansinger-build-it-figma-ai', 'jordansinger/build-it-figma-ai', 'https://github.com/jordansinger/build-it-figma-ai', 'Figma AI 예제 | 자동화 | 자동화 구현예제', 'image', false),
  ('leonardo.ai', 'Leonardo.AI', 'https://leonardo.ai/', '이미지 생성 | 소재/게임아트 | 게임 아트 특화', 'image', false),
  ('magnific-ai', 'Magnific AI', 'https://magnific.ai/', 'AI 이미지 업스케일링 | 저해상도 이미지 고품질 확대 시 | 업스케일 특화 최강', 'image', false),
  ('microsoft-designer', 'Microsoft Designer - 순식간에 멋진 디자인을 만드세요.', 'https://designer.microsoft.com/', 'AI 디자인 도구 | 빠른 디자인 생성 시 | MS 생태계 통합', 'image', false),
  ('midjourney', 'Midjourney', 'https://www.midjourney.com/', '이미지 생성 | 스타일 | 예술적 스타일특화', 'image', false),
  ('mockuper.net-free-custom-mockups-generator', 'Mockuper.net | Free custom mockups generator', 'https://mockuper.net/', NULL, 'image', false),
  ('recraft-v3', 'Recraft v3', 'https://recraft.ai/', 'SVG·벡터·브랜드 이미지 | 일관된 브랜드 비주얼 제작 시 | 벡터 생성 유일', 'image', false),
  ('stable-diffusion', 'Stable Diffusion', 'https://stability.ai/', '이미지 생성 | Stable Diffusion | 오픈소스+커스터마이징', 'image', false),
  ('teachable-machine', 'Teachable Machine', 'https://teachablemachine.withgoogle.com/train', '노코드 ML | 분류 모델 | 쉬운 모델생성', 'image', false),
  ('whisk', 'Whisk', 'https://labs.google/fx/tools/whisk', '이미지 프롬프트 | 조합 | 이미지 조합생성', 'image', false),
  ('anthropic-api', 'Anthropic API', 'https://www.anthropic.com/', 'Anthropic | 모델/문서 | Claude API 접근', 'platform', false),
  ('api-keys-openai-api', 'API keys - OpenAI API', 'https://platform.openai.com/api-keys', 'API 키 관리 | 키 발급/회전 | 유출방지+권한제어', 'platform', false),
  ('aws-secrets-manager-best-practices', 'AWS Secrets Manager best practices', 'https://docs.aws.amazon.com/secretsmanager/latest/userguide/best-practices.html', '시크릿 관리 | 운영 보안 | 비밀키 안전관리', 'platform', false),
  ('aws-waf-rate-based-request-limiting', 'AWS WAF rate-based request limiting', 'https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-rate-based-request-limiting.html', 'WAF 레이트리밋 | 트래픽 방어 | 과도한 요청 차단', 'platform', false),
  ('billing-overview-openai-api', 'Billing overview - OpenAI API', 'https://platform.openai.com/settings/organization/billing/overview', '과금/사용량 | 비용 튈 때 | 조직 단위 비용 추적', 'platform', false),
  ('cost-tracking-guide', 'Cost tracking guide', 'https://docs.helicone.ai/guides/cookbooks/cost-tracking', '비용 추적 | 비용 분석 | 비용 분석 방법론', 'platform', false),
  ('github.com-berriai-litellm', 'github.com/BerriAI/litellm', 'https://github.com/BerriAI/litellm', 'LiteLLM 코드 | 셀프호스트 | 직접 운영 가능', 'platform', false),
  ('graph_recursion_limit', 'GRAPH_RECURSION_LIMIT 문서', 'https://docs.langchain.com/oss/python/langgraph/errors/GRAPH_RECURSION_LIMIT', 'LangGraph 에러 | recursion | 재귀 에러 해결법', 'platform', false),
  ('helicone', 'Helicone', 'https://www.helicone.ai/', 'LLM 관측 | 비용/로그 | 실서비스 모니터링', 'platform', false),
  ('litellm-proxy-ai-gateway', 'LiteLLM Proxy (AI Gateway)', 'https://docs.litellm.ai/docs/simple_proxy', 'LLM 게이트웨이 | 멀티모델 | 여러 모델 통합관리', 'platform', false),
  ('microsoft-presidio-pii', 'Microsoft Presidio (PII 탐지/마스킹)', 'https://github.com/microsoft/presidio', 'PII 탐지 | 로그/텍스트 | 개인정보 자동마스킹', 'platform', false),
  ('openai-api', 'OpenAI API', 'https://platform.openai.com/', 'OpenAI 콘솔 | API 설정 | 공식 문서 참고처', 'platform', false),
  ('openai-batch-api', 'OpenAI Batch API', 'https://platform.openai.com/docs/guides/batch', '비동기 배치 | 대량 처리 | 대량처리시 50%절감', 'platform', false),
  ('openai-prompt-caching', 'OpenAI Prompt caching', 'https://platform.openai.com/docs/guides/prompt-caching', '프롬프트 캐시 | 비용/지연 | 반복 요청시 비용절감', 'platform', false),
  ('pangea-ai-guard-pii-redaction-prompt-injection', 'Pangea AI Guard (PII redaction, prompt injection 등)', 'https://pangea.cloud/docs/ai-guard', 'AI 보안 | 인젝션/PII | 공격 차단+필터링', 'platform', false),
  ('papers-with-code', 'Papers with Code', 'https://paperswithcode.com/', '논문+코드 | 구현 찾기 | SOTA 성능 비교', 'platform', false),
  ('replicate-run-ai-with-an-api', 'Replicate - Run AI with an API', 'https://replicate.com/', '모델 API 플랫폼 | 오픈소스 모델 실행 시 | 원클릭 API 서빙', 'platform', false),
  ('tokenizer-openai-api', 'Tokenizer - OpenAI API', 'https://platform.openai.com/tokenizer', '토큰 계산 | 비용 산정 | 과금폭탄 사전방지', 'platform', false),
  ('weights-biases', 'Weights & Biases', 'https://wandb.ai/site/', 'AI 실험 추적 플랫폼 | 모델 학습·실험 로깅 시 | W&B 대시보드', 'platform', false),
  ('alphaxiv', 'AlphaXiv', 'https://alphaxiv.org/', '논문 토론 | 리뷰/댓글 | 커뮤니티 논문 토론', 'research', false),
  ('app', '라이너', 'https://app.liner.com/ko', 'AI 하이라이트 | 리서치 중 | 중요구절 표시+저장', 'research', false),
  ('arxiv', 'arXiv', 'https://arxiv.org/', '논문 아카이브 | 최신 논문 | 리뷰전 원문접근', 'research', false),
  ('semantic-scholar', 'Semantic Scholar', 'https://www.semanticscholar.org/', '논문 검색 | 관련 연구 | 인용 관계 시각화', 'research', false),
  ('eddie-ai-the-assistant-video-editor-for-pros', 'Eddie AI | the Assistant Video Editor for Pros', 'https://www.heyeddie.ai/', 'AI 영상 편집 어시스턴트 | 영상 편집 자동화 시 | 프로용 AI 편집 도구', 'video', false),
  ('flow', 'Flow', 'https://labs.google/flow/about', '구글 영상 제작 | 오디오+영상 생성 | 아이디어 시각화', 'video', false),
  ('google-veo-3.1', 'Google Veo 3.1', 'https://labs.google/veo', '영상+오디오 동시 생성 | 고품질 영상 콘텐츠 제작 시 | 현재 품질 최상위', 'video', false),
  ('hailuo-ai', 'Hailuo AI', 'https://hailuoai.video/', 'MiniMax 영상 생성 | 빠르고 저렴한 영상 필요 시 | 속도·가성비 최적화', 'video', false),
  ('higgsfield-ai', 'Higgsfield AI', 'https://higgsfield.ai/', '영상 AI 모델 통합 플랫폼 | 다양한 모델 비교·사용 시 | Sora·Kling·Veo 한곳에서', 'video', false),
  ('kling-2.6', 'Kling 2.6', 'https://kling.kuaishou.com/', '고품질 영상 생성 | 가성비 영상 AI 필요 시 | TOP3 성능 최저 비용', 'video', false),
  ('klingai', 'KlingAI', 'https://klingai.com/global/', '영상 생성 | Kling | 이미지→영상 변환', 'video', false),
  ('luma-ai', 'Luma AI', 'https://lumalabs.ai/', '영상 생성 | Dream Machine | Luma 영상모델', 'video', false),
  ('pika', 'Pika', 'https://pika.art/', '영상 생성 | 짧은클립 | 짧은 클립 특화', 'video', false),
  ('runway-ml', 'Runway ML', 'https://runwayml.com/', '영상 생성 | 편집/Gen | 영상 편집+생성', 'video', false),
  ('sora', 'Sora', 'https://sora.chatgpt.com/', '영상 생성 | Sora | 고품질 영상생성', 'video', false),
  ('sora-2', 'Sora 2', 'https://sora.com/', 'OpenAI 영상 생성 | 텍스트→고품질 영상 필요 시 | OpenAI 생태계 영상', 'video', false),
  ('typecast', 'typecast', 'https://typecast.ai/kr', 'TTS/더빙 | 한국어 | 한국어 더빙특화', 'video', false),
  ('canny', 'Canny', 'https://canny.io/', '피드백 보드 | 요청 수집 | 우선순위 투표기능', 'workflow', false),
  ('dovetail', 'Dovetail', 'https://dovetail.com/', '리서치 정리 | 인터뷰 | 인터뷰 내용 체계정리', 'workflow', false),
  ('fullstory', 'Fullstory', 'https://www.fullstory.com/platform/session-replay/', '세션 리플레이 | 버그 재현 | 버그 발생 원인추적', 'workflow', false),
  ('hotjar', 'Hotjar', 'https://www.hotjar.com/', '히트맵/리플레이 | UX 분석 | 클릭패턴 시각화', 'workflow', false),
  ('intercom', 'Intercom', 'https://www.intercom.com/', 'CS 채팅 | 고객 응대 | 인앱 실시간 응대', 'workflow', false),
  ('jira', 'Jira', 'https://ming2tofu33.atlassian.net/jira/for-you', '이슈 트래킹 | 스프린트 | 스프린트 기반 관리', 'workflow', false),
  ('make', 'Make', 'https://us2.make.com/organization/5502534/dashboard', '자동화 | 시나리오 | 시나리오 기반 자동화', 'workflow', false),
  ('marketplace-profile-notion', 'Marketplace Profile | Notion', 'https://www.notion.so/profile/integrations', '크리에이터 프로필 | 템플릿 판매 | 템플릿 수익화', 'workflow', false),
  ('maze', 'Maze', 'https://maze.co/', '사용성 테스트 | 프로토타입 | 사용성 검증+피드백', 'workflow', false),
  ('metabase', 'Metabase', 'https://www.metabase.com/', 'BI 대시보드 | SQL/차트 | SQL→차트 자동변환', 'workflow', false),
  ('mixpanel', 'Mixpanel', 'https://mixpanel.com/platform/product-analytics/', '제품 분석 | 퍼널/리텐션 | 사용자 행동 추적', 'workflow', false),
  ('n8n', 'n8n', 'https://n8n.io/', '워크플로우 | 자동화 | 오픈소스 워크플로우', 'workflow', false),
  ('notion-prd-templates', 'Notion PRD templates', 'https://www.notion.com/ko/templates/category/product-requirements-doc', 'PRD 템플릿 | 기획 문서 | 빠른 기획서 작성', 'workflow', false),
  ('pandarank', '판다랭크', 'https://pandarank.net/', '마케팅 분석 | 키워드/SEO | 네이버 SEO분석', 'workflow', false),
  ('pipedream', 'Pipedream', 'https://pipedream.com/', '워크플로우 | 코드+연결 | 코드+노코드 혼합', 'workflow', false),
  ('posthog', 'PostHog', 'https://posthog.com/docs/experiments/creating-an-experiment', '제품 분석/실험 | A/B 테스트 | 데이터 직접관리', 'workflow', false),
  ('posthog-a-b-testing', 'PostHog A/B testing 가이드', 'https://posthog.com/product-engineers/how-to-do-ab-testing', '제품 분석/실험 | A/B 테스트 | 실험 설계 방법론', 'workflow', false),
  ('productboard', 'Productboard', 'https://www.productboard.com/', '제품 로드맵 | 우선순위 | 로드맵 관리+공유', 'workflow', false),
  ('statsig', 'Statsig', 'https://docs.statsig.com/feature-flags/overview', 'Feature flag | 실험 롤아웃 | 기능 점진배포', 'workflow', false),
  ('tally', 'Tally', 'https://tally.so/', '폼 빌더 | 간단 설문 | 빠른 폼 제작', 'workflow', false),
  ('tldraw', 'tldraw', 'https://makereal.tldraw.com/', '스케치→UI | 프로토타입 | 스케치→코드 변환', 'workflow', false),
  ('typeform', 'Typeform', 'https://www.typeform.com/', '설문 폼 | 사용자 조사 | UX 피드백 수집', 'workflow', false),
  ('zapier', 'Zapier', 'https://zapier.com/app/home', '자동화 | SaaS 연결 | SaaS 앱 자동연결', 'workflow', false),
  ('zendesk', 'Zendesk', 'https://www.zendesk.kr/service/#georedirect', '헬프데스크 | 티켓 관리 | 고객 문의 체계관리', 'workflow', false)
ON CONFLICT (slug) DO NOTHING;